---
driver:
  name: ec2

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    image_id: ami-f95ef58a

verifier:
  name: inspec
  format: doc

transport:
  ssh_key: /home/atlassian/.ssh/bamboo

suites:
  - name: default
    run_list: ntp::default
    attributes:
      ntp:
        sync_clock: true
        sync_hw_clock: true
